### ISSUE TITLE
No module named 'typer'

### ISSUE THREAD

**Issue by Lambru99** [daxAKAhackerman/testing-tor-network#6]
Hi, I execute the `make` command and all seems to be correct, I'm in the venv that the MakeFile create for me, I'm trying to run `python cli/main.py --help` but it says to me:

`File "[...]/testing-tor-network/cli/main.py", line 5, in <module>
    import typer
ModuleNotFoundError: No module named 'typer'`

I tried to update pip with `pip install --upgrade pip` and to install the pack with `pip install typer` but it say:

`Requirement already satisfied: typer in .local/share/virtualenvs/testing-tor-network-dP7JrAnl/lib/python3.12/site-packages (0.12.5)
Requirement already satisfied: click>=8.0.0 in .local/share/virtualenvs/testing-tor-network-dP7JrAnl/lib/python3.12/site-packages (from typer) (8.1.7)
Requirement already satisfied: typing-extensions>=3.7.4.3 in .local/share/virtualenvs/testing-tor-network-dP7JrAnl/lib/python3.12/site-packages (from typer) (4.12.2)
Requirement already satisfied: shellingham>=1.3.0 in .local/share/virtualenvs/testing-tor-network-dP7JrAnl/lib/python3.12/site-packages (from typer) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in .local/share/virtualenvs/testing-tor-network-dP7JrAnl/lib/python3.12/site-packages (from typer) (13.8.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in .local/share/virtualenvs/testing-tor-network-dP7JrAnl/lib/python3.12/site-packages (from rich>=10.11.0->typer) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in .local/share/virtualenvs/testing-tor-network-dP7JrAnl/lib/python3.12/site-packages (from rich>=10.11.0->typer) (2.18.0)
Requirement already satisfied: mdurl~=0.1 in .local/share/virtualenvs/testing-tor-network-dP7JrAnl/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer) (0.1.2)`

**Comment by daxAKAhackerman** [comment]
Hi! Looks live the venv is not activated or something 🤔 Might be related to your installation of pipenv, or maybe the Python version. I've added a `requirements.txt` to the repository so you can create the virtual environment yourself using:

```bash
python -m venv .env
source .env/bin/activate
pip install -r requirements.txt
python cli/main.py --help
```

Give this a try and let me know if it works!

**Comment by Lambru99** [comment]
Thank I'm gonna try it, for the moment I used the medium tutorial and all work first try

**Comment by daxAKAhackerman** [comment]
Ah glad to hear it! Don't hesitate to open an other issue if you experience other problems!
